import styles from '../styles/Join.module.css';
import Image from 'next/image'
import Head from 'next/head'
import Link from 'next/link'

let input_fields = [ //Para poner los nombres por defecto de los campos,
    //y el nombre de la correspondiente propiedad en user_to_send
    ["Usuario", "username"],
    ["Correo", "email"],
    ["Género","gender"],
    ["País","country"], 
    ["Contraseña","password"],
    ["Repetir Contraseña","rep_password"]
];

let user_to_send:object = {
    username:"",
    email:"",
    gender:"",
    country:"",
    password:"",
    rep_password:"",
}

let url = '/api/handleJoinRequest'

const log_butt = '/buttons/LOG-IN.png';
const join_butt = '/buttons/JOIN.png';

export default function Join (){
    return (
        <div>
            <Head>
                <title>Join PPC Games</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>          
                <div className = {styles.Background}>
                    <div className = {styles.AllInside}>
                        <div className = {styles.logo}>
                            <Image
                            src="/pages_imgs/logo_PPC.png"
                            alt="Logo de PPC Games"
                            width={200}
                            height={300}
                            priority                    
                            />
                        </div>
                        <h2>Únete a PPC Games</h2>
                        <form>
                            <div className={styles.gridInputs}>
                                {input_fields.map((field, index)=>{
                                    return (                            
                                        <input             
                                            key={index}
                                            type="text" 
                                            placeholder={field[0]}
                                            onChange={(e)=>{
                                                e.preventDefault();
                                                user_to_send[field[1]] = e.target.value;
                                            }}>                                                                                        
                                        </input>
                                    );
                                })}
                            </div>
                            <div className = {styles.LoginButton}>
                                <PPCButtons/>
                            </div>
                        </form>
                        <div className={styles.loginLink}>
                            <h3>
                                <Link href="/">¿Ya tienes una cuenta? Inicia sesión acá</Link>
                            </h3>
                        </div>        
                        <footer>
                            <h3>PPC - 2023</h3>
                            <h3>Copyright © PPC Team Ltd</h3>
                        </footer>
                    </div>    
                </div>
            </main>
        </div>
        
    );
}

function PPCButtons(props: object){
    async function handleClick(){
        const response = await fetch(url, {
            method: "PUT",
            body: JSON.stringify(user_to_send),
        });
        const json = await response.json();
        console.log(json);
    }
    return (
        <button type="button"
         onClick={handleClick} 
         className={styles.Buttons}>    
        </button>
    );
}