import styles from '../styles/Join.module.css';
import Image from 'next/image'
import Head from 'next/head'

let input_fields = [
    "Usuario", "Correo", "Género", "País", "Contraseña",
    "Repetir Contraseña"
];

const log_butt = '/buttons/LOG-IN.png';
const join_butt = '/buttons/JOIN.png';

export default function Join (){
    return (
        <div>
            <Head>
                <title>Join PPC Games</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <h1 className = {styles.ProvTitle}>Creando Página Registro</h1>
                <div className = {styles.bg}                >
                    <div className = {styles.AllInside}>
                        <div className = {styles.logo}>
                            <Image
                            src="/pages_imgs/logo_PPC.png"
                            alt="Logo de PPC Games"
                            width={200}
                            height={300}
                            priority                    
                            />
                        </div>
                        <h2 className={styles.CenteredText}>Únete a PPC Games</h2>
                        <form>
                            <div className={styles.gridInputs}>
                                {input_fields.map((inp)=>{
                                    return <Input text={inp}></Input>
                                })}
                            </div>
                            <div className={styles.LoginButton}>
                                <PPCButts url={log_butt}/>
                            </div>
                        </form>
                    </div>    
                </div>
            </main>
        </div>
        
    );
}

function Input(props: object){
    const { text } = props;
    return(
        <input
        type = "text"
        defaultValue={text}>

        </input>
    );
}

function PPCButts(props: object){
    const { url } = props;
    function handleClick(){
        alert("El botón funciona");
    }
    return (
        <button
        onClick={handleClick}>
            <img src={url} alt = 'Loguearse'></img>
        </button>
    );
}