import styles from '../styles/Main.module.css';
import Head from 'next/head'
import { useRouter } from 'next/router'
import Link from 'next/link';
import Image from 'next/image';

type jsAnswer = {
    name: string;
}

const startButton = '/sprites/generalAssets/START GAME.png';
const profileButton = '/sprites/generalAssets/PROFILE.png';
const rankingButton = '/sprites/generalAssets/RANKINGS.png';
const aspectButton = '/sprites/generalAssets/ASPECT.png';
const gachaButton = '/sprites/generalAssets/GACHA.png';
const logoutButton = '/sprites/generalAssets/LOG-OUT.png';

export default function Main (){
    return (
        <div>
            <Head>
                <title>PPC Games</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <div className = {styles.background}>
                    <div className= {styles.allInside}>
                        <div className = {styles.logoDiv}>
                            <img 
                                src="/backgrounds/logo_PPC.png"
                                className={styles.logo}>
                            </img> 
                        </div>
                        <h1 className= {styles.title}>BIENVENIDO A PPC GAMES</h1>
                        <Buttons/>
                    </div>    
                </div>
            </main>
        </div>
    );
}

function Buttons() {

    return (
        <div>
            <div className= {styles.buttonDiv1}> 
                <StartButton/>
                <ProfileButton/>
                <RankingButton/>
            </div>
            <div className= {styles.buttonDiv2}> 
                <AspectButton/>
                <GachaButton/>
                <LogOutButton/>
            </div>
        </div>
    );
}

function StartButton(){
    //Cuando se presiona el botón, se redirecciona al juego

    const router = useRouter()

    function showMessageScreen (js: jsAnswer) {
        console.log(js);
    }   

    async function startGame(){
        showMessageScreen({name: "Iniciando Juego..."})
        router.push('/game')
    }

    return (
        <Link
        className={styles.PPCButton}
        style={{ width: '15%' }}
        onClick = {startGame}
        href={'/game'}>
            <img src={"/sprites/generalAssets/START GAME.png"}></img>
        </Link>
    )
}

function ProfileButton(){
    //Cuando se presiona el botón, se redirecciona al perfil del jugador

    const router = useRouter()

    function showMessageScreen (js: jsAnswer) {
        console.log(js);
    }

    async function openProfile(){
        showMessageScreen({name: "Entrando al perfil del jugador..."})
        router.push('/profile')
    }
    
    return (
        <Link
        className={styles.PPCButton}
        style={{ width: '15%' }}
        onClick = {openProfile}
        href={'/gacha'}>
            <img src={"/sprites/generalAssets/PROFILE.png"}></img>
        </Link>
    );
}

function RankingButton(){
    //Cuando se presiona el botón, se redirecciona a la tabla de ranking

    const router = useRouter()

    function showMessageScreen (js: jsAnswer) {
        console.log(js);
    }

    async function openRanking(){
        showMessageScreen({name: "Entrando a el Ranking..."})
        router.push('/rankings')
    }
    
    return (
        <Link
        className={styles.PPCButton}
        style={{ width: '15%' }}
        onClick = {openRanking}
        href={'/rankings'}>
            <img src={"/sprites/generalAssets/RANKINGS.png"}></img>
        </Link>
    );
}


function AspectButton(){
    //Cuando se presiona el botón, se redirecciona al menu de cambio de aspecto

    const router = useRouter()

    function showMessageScreen (js: jsAnswer) {
        console.log(js);
    }

    async function openAspect(){
        showMessageScreen({name: "Entrando a el menu de personalizacion..."})
        router.push('/customization')
    }
    
    return (
        <Link
        className={styles.PPCButton}
        style={{ width: '15%' }}
        onClick = {openAspect}
        href={'/customization'}>
            <img src={"/sprites/generalAssets/ASPECT.png"}></img>
        </Link>
    );
}

function GachaButton(){
    //Cuando se presiona el botón, se redirecciona al gacha

    const router = useRouter()
 
    function showMessageScreen (js: jsAnswer) {
        console.log(js);
    }

    async function openGacha(){
        showMessageScreen({name: "Entrando al GACHA..."})
        router.push('/gacha')
    }
    
    return (
        <Link
        className={styles.PPCButton}
        style={{ width: '15%' }}
        onClick = {openGacha}
        href={'/gacha'}>
            <img src={"/sprites/generalAssets/GACHA.png"}></img>
        </Link>
    );
}

function LogOutButton(){
    //Cuando se presiona el botón, se cierra la sesión
    const router = useRouter()

    async function logout(){
        await fetch('/api/getSessions',{
            method: "DELETE",
        })
        router.push('/login')
    }
    
    return (
        <Link
        className={styles.PPCButton}
        style={{ width: '15%' }}
        onClick={logout}
        href={'/login'} 
                >
            <img src={"/sprites/generalAssets/LOG-OUT.png"} alt="Logout Button" />
        </Link>
    );
}